### ISSUE TITLE
formatIMGT.sh NullPointerException

### ISSUE THREAD

**Issue by zezzipa** [Kingsford-Group/kourami#19]
Hi again,

I have downloaded the Alignments_Rel_3330.zip from https://github.com/ANHIG/IMGTHLA and put the hla_nom_g.txt in that folder. It seem to be working fine at first to create the new reference with formatIMGT.sh but then it crashes, the last part of the log is as follow:

>>>>>>>>>  Processing   [Y]  <<<<<<<<<<
nucRefAl:       Y*01:01 genRefAl:       Y*01:01
        refGeneName on nuc and gen are same
        Wrting to :     /proj/uppstore2018100/kourami-0.9.6/scripts/../custom_db/3.33.0/Y_gen.txt
        Wrting to :     /proj/uppstore2018100/kourami-0.9.6/scripts/../custom_db/3.33.0/Y_nuc.txt
REF SEQ names differs :
(nuc):Y*01:01
(gen):Y
java.lang.NullPointerException
        at Sequence.processBlock(Sequence.java:554)
        at Sequence.<init>(Sequence.java:498)
        at MergeMSFs.mergeAndAdd(MergeMSFs.java:383)
        at MergeMSFs.mergeAndAdd(MergeMSFs.java:372)
        at MergeMSFs.merge(MergeMSFs.java:298)
        at FormatIMGT.processGene(FormatIMGT.java:199)
        at FormatIMGT.main(FormatIMGT.java:100)

Any idea what the problem might be?
Thank you in advance for the help!

**Comment by zezzipa** [comment]
And as a follow-up on that question, is there a way to include MICA, MICB, TAP1 and TAP2 in the output. These genes are of interest to us in the disease we are studying and it would be great if we could get information for all genes from the same software.

**Comment by zezzipa** [comment]
Thank you for looking into this. So irritating when they change format. I already had that problem another time this week.

I downloaded the new version, I had a problem with DRB5_gen.txt now (with IMGT/HLA version 3.34.0). 

>>>>>>>>>  Processing   [DRB5]  <<<<<<<<<<
nucRefAl:       DRB1*01:01:01   genRefAl:       DRB5*01:01:01
        refGeneName on nuc and gen are NOT same
Reference sequence entry [DRB5*01:01:01] is NOT found in nuc alignments.
Check the alignment files.

I fixed it by changing name on the allele in the DRB5_gen.txt file, since I don't care about DRB5 that worked for me. But for the future, with someone that does care, it can be good to look into. 
Now I have a new reference, thank you so much!

I understand, it is not possible to do everything at once.

**Comment by heewookl** [comment]
Hi,

I didnt bother checking what was new in 3.34.0 release. Addition of an allele of DRB5 in the release, DRB5_gen.txt has been newly added in the release. I understand you don't care about DRB5 sequences, but I suggest you to use 3.33.0 release for the time being rather than modifying allele names to get away with the error. I should be able to get to this early Nov along with a possiblity of supporting MICA/B and TAP1/2.

**Comment by droe-nmdp** [comment]
Is there any update on this or suggestions as to a work around?

**Comment by mmaiers-nmdp** [comment]
Actually the DRB5_gen.txt that comes in the Alignments_Rel_3360.zip has the right name so everything works if you just comment out the part in scripts/formatIMGT.sh where it overwrites the file from the resources directory

**Comment by davetang** [comment]
Thank you @mmaiers-nmdp. `scripts/formatIMGT.sh` works with release 3.40.0, if I comment out the following lines (or remove the code block).

```
if [ ! -e "$resource_dir/DRB5_gen.txt" ];then
    echo "Missing DRB5_gen.txt in the resource directory. Please git pull or git clone"
    exit 1
# else
# cp $resource_dir/DRB5_gen.txt $input_msa/.
fi
```

**Comment by masen0407** [comment]
Hi,@heewookl 
i have try HLA Release 3.40.0 and HLA Release 3.41.0,they all go wrong with DRB5.
And i noticed that Release 3.40.0 and HLA Release 3.41.0 noly have DRB_nuc.txt,but with DRB1_gen.txt,DRB3_gen.txt,DRB4_gen.txt,DRB5_gen.txt 4 splitted gene.txt file.so it make scripts/formatIMGT.sh can not work with the new  release.
can you work with this problems?
Thank you

**Comment by freshfischer** [comment]
> Hi again,
> 
> I have downloaded the Alignments_Rel_3330.zip from https://github.com/ANHIG/IMGTHLA and put the hla_nom_g.txt in that folder. It seem to be working fine at first to create the new reference with formatIMGT.sh but then it crashes, the last part of the log is as follow:
> 
> > > > > > > > > > Processing   [Y]  <<<<<<<<<<
> > > > > > > > > > nucRefAl:       Y_01:01 genRefAl:       Y_01:01
> > > > > > > > > > refGeneName on nuc and gen are same
> > > > > > > > > > Wrting to :     /proj/uppstore2018100/kourami-0.9.6/scripts/../custom_db/3.33.0/Y_gen.txt
> > > > > > > > > > Wrting to :     /proj/uppstore2018100/kourami-0.9.6/scripts/../custom_db/3.33.0/Y_nuc.txt
> > > > > > > > > > REF SEQ names differs :
> > > > > > > > > > (nuc):Y*01:01
> > > > > > > > > > (gen):Y
> > > > > > > > > > java.lang.NullPointerException
> > > > > > > > > > at Sequence.processBlock(Sequence.java:554)
> > > > > > > > > > at Sequence.(Sequence.java:498)
> > > > > > > > > > at MergeMSFs.mergeAndAdd(MergeMSFs.java:383)
> > > > > > > > > > at MergeMSFs.mergeAndAdd(MergeMSFs.java:372)
> > > > > > > > > > at MergeMSFs.merge(MergeMSFs.java:298)
> > > > > > > > > > at FormatIMGT.processGene(FormatIMGT.java:199)
> > > > > > > > > > at FormatIMGT.main(FormatIMGT.java:100)
> 
> Any idea what the problem might be?
> Thank you in advance for the help!

This problem happens when java cannot identifiy allele "Y*01:01" correctly due to ' * ' in the first base position in  file  Y_gene.txt,  script works after deleting the first alignment position base.

**Comment by danilovkiri** [comment]
@freshfischer hi, thank you for your comment. Could you please explain what do you mean by "deleting the first alignment position base"? Am I getting it correctly below? Do I need to change the `-1` gDNA position to `0` and remove asterisks/`G` and spaces that come before the pipe in the sequence coding lines starting with `Y*...`?

```
# file: Y_gen.txt
# date: 2020-10-15
# version: IPD-IMGT/HLA 3.42.0
# origin: http://hla.alleles.org/wmda/Y_gen.txt
# repository: https://raw.githubusercontent.com/ANHIG/IMGTHLA/Latest/alignments/Y_gen.t>
# author: Steven G. E. Marsh (steven.marsh@ucl.ac.uk)

 gDNA              -1
                    |
 Y*01:01           * | ATGGCGGTC GTGGCGCCCC GAACCCTCCT CCTGCTACTC TCGGGGGCCC TGGCCCTGAC>
 Y*02:01           G | --------- ---------- ---------- ---------- ---------- ---------->
 Y*03:01           * | --------- ---------- ---------- ---------- ---------- ---------->

```

**Comment by freshfischer** [comment]
> @freshfischer hi, thank you for your comment. Could you please explain what do you mean by "deleting the first alignment position base"? Am I getting it correctly below? Do I need to change the `-1` gDNA position to `0` and remove asterisks/`G` and spaces that come before the pipe in the sequence coding lines starting with `Y*...`?
> 
> ```
> # file: Y_gen.txt
> # date: 2020-10-15
> # version: IPD-IMGT/HLA 3.42.0
> # origin: http://hla.alleles.org/wmda/Y_gen.txt
> # repository: https://raw.githubusercontent.com/ANHIG/IMGTHLA/Latest/alignments/Y_gen.t>
> # author: Steven G. E. Marsh (steven.marsh@ucl.ac.uk)
> 
>  gDNA              -1
>                     |
>  Y*01:01           * | ATGGCGGTC GTGGCGCCCC GAACCCTCCT CCTGCTACTC TCGGGGGCCC TGGCCCTGAC>
>  Y*02:01           G | --------- ---------- ---------- ---------- ---------- ---------->
>  Y*03:01           * | --------- ---------- ---------- ---------- ---------- ---------->
> ```

As for this problem, I just re-edit `Y_gen.txt` like this to make it identified by java:

```
> Nuc+Gen merged MSA for Kourami
> # file: Y_gen.txt
> # date: 2020-04-20
> # version: IPD-IMGT/HLA 3.40.0
> # origin: http://hla.alleles.org/wmda/Y_gen.txt
> # repository: https://raw.githubusercontent.com/ANHIG/IMGTHLA/Latest/alignments/Y_gen.txt
> # author: WHO, Steven G. E. Marsh (steven.marsh.ac.uk)
>                    
>  gDNA              0                                                                                   
>                    |                                                                                 
>  Y*01:01            ATGGCGGTC GTGGCGCCCC GAACCCTCCT CCTGCTACTC TCGGGGGCCC TGGCCCTGAC CCAGACCTGG GCGG 
>  Y*02:01            --------- ---------- ---------- ---------- ---------- ---------- ---------- ---- 
>  Y*03:01            --------- ---------- ---------- ---------- ---------- ---------- ---------- ---- 
```

**Comment by davetang** [comment]
> > Hi again,
> > I have downloaded the Alignments_Rel_3330.zip from https://github.com/ANHIG/IMGTHLA and put the hla_nom_g.txt in that folder. It seem to be working fine at first to create the new reference with formatIMGT.sh but then it crashes, the last part of the log is as follow:
> > > > > > > > > > > Processing   [Y]  <<<<<<<<<<
> > > > > > > > > > > nucRefAl:       Y_01:01 genRefAl:       Y_01:01
> > > > > > > > > > > refGeneName on nuc and gen are same
> > > > > > > > > > > Wrting to :     /proj/uppstore2018100/kourami-0.9.6/scripts/../custom_db/3.33.0/Y_gen.txt
> > > > > > > > > > > Wrting to :     /proj/uppstore2018100/kourami-0.9.6/scripts/../custom_db/3.33.0/Y_nuc.txt
> > > > > > > > > > > REF SEQ names differs :
> > > > > > > > > > > (nuc):Y*01:01
> > > > > > > > > > > (gen):Y
> > > > > > > > > > > java.lang.NullPointerException
> > > > > > > > > > > at Sequence.processBlock(Sequence.java:554)
> > > > > > > > > > > at Sequence.(Sequence.java:498)
> > > > > > > > > > > at MergeMSFs.mergeAndAdd(MergeMSFs.java:383)
> > > > > > > > > > > at MergeMSFs.mergeAndAdd(MergeMSFs.java:372)
> > > > > > > > > > > at MergeMSFs.merge(MergeMSFs.java:298)
> > > > > > > > > > > at FormatIMGT.processGene(FormatIMGT.java:199)
> > > > > > > > > > > at FormatIMGT.main(FormatIMGT.java:100)
> > 
> > 
> > Any idea what the problem might be?
> > Thank you in advance for the help!
> 
> This problem happens when java cannot identifiy allele "Y*01:01" correctly due to ' * ' in the first base position in file Y_gene.txt, script works after deleting the first alignment position base.

If you use the latest update of this repository (commit https://github.com/Kingsford-Group/kourami/commit/545c770e078f81fc9aee7685ce3914c8a5970911) instead of the latest release tag (v0.9.6), you don't get that particular error.
