### ISSUE TITLE
Null Pointer on Kourami call

### ISSUE THREAD

**Issue by j2moreno** [Kingsford-Group/kourami#25]
I am getting a Null Pointer error while running Kourami on a custom built IMGT HLA alignments version 3.37.0 and using 1000 genomes NA12878 GRCh38 aligned bam file. I went through the steps explained in https://github.com/Kingsford-Group/kourami/blob/master/preprocessing.md to prepare the custom database and prepare the bam file. Both completed successfully but I am getting the following error message: 

IMGT HLA 3.37.0 alignment files
https://github.com/ANHIG/IMGTHLA/tree/Latest/alignments

The 1000 genomes NA12878 GRCh38 aligned bam file
ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000_genomes_project/data/CEU/NA12878/alignment/NA12878.alt_bwamem_GRCh38DH.20150718.CEU.low_coverage.cram

```
>>>>>>>>>>>>>>>> extracting reads mapping to HLA loci and ALT contigs (38DH)
[bam_sort_core] merging from 0 files and 8 in-memory blocks...
>>>>>>>>>>>>>> indexing extracted bam (38DH)
>>>>>>>>>>>>>> bamUtil fastq extraction (38DH)
>>>>>>>>>>>>>> Mapping back to GRCh38_NoALT_wHLA (38DH_NoAlt)
[M::bwa_idx_load_from_disk] read 3171 ALT contigs
[M::process] read 491302 sequences (49621502 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 54, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (365, 385, 395)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (305, 455)
[M::mem_pestat] mean and std.dev: (379.52, 24.97)
[M::mem_pestat] low and high boundaries for proper pairs: (275, 485)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 491302 reads in 257.462 CPU sec, 32.830 real sec
[main] Version: 0.7.15-r1140
[main] CMD: /usr/local/bin/bwa mem -t 8 /shares/hii/bioinfo/ref/gotcloud/hs38DH-db142-v1/hs38DH.fa test_tmp.extract_1.fq.gz test_tmp.extract_2.fq.gz
[main] Real time: 52.121 sec; CPU: 266.018 sec
[bam_sort_core] merging from 0 files and 8 in-memory blocks...
[bam_sort_core] merging from 0 files and 8 in-memory blocks...
>>>>>>>>>>>>>> indexing extracted bam (38DH_NoAlt)
>>>>>>>>>>>>>> bamUtil fastq extraction (38DH_NoAlt)
>>>>>>>>>>>>>> bwa mem to hla panel for Kourami
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 31954 sequences (3227354 bp)...
[M::mem_pestat] # candidate unique pairs for (FF, FR, RF, RR): (0, 710, 0, 0)
[M::mem_pestat] skip orientation FF as there are not enough pairs
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] skip orientation FF as there are not enough pairs                                                                                             [61488/301933]
[M::mem_pestat] analyzing insert size distribution for orientation FR...
[M::mem_pestat] (25, 50, 75) percentile: (356, 383, 404)
[M::mem_pestat] low and high boundaries for computing mean and std.dev: (260, 500)
[M::mem_pestat] mean and std.dev: (380.44, 32.22)
[M::mem_pestat] low and high boundaries for proper pairs: (212, 548)
[M::mem_pestat] skip orientation RF as there are not enough pairs
[M::mem_pestat] skip orientation RR as there are not enough pairs
[M::mem_process_seqs] Processed 31954 reads in 63.380 CPU sec, 7.992 real sec
[main] Version: 0.7.15-r1140
[main] CMD: /usr/local/bin/bwa mem -t 8 /home/j/jmoreno8/dev/usf-hii/fac-parikhh-teddy-hla-imputation/tmp/kourami_db/3.37.0/All_FINAL_with_Decoy.fa.gz test_extract_1.fq.gz
test_extract_2.fq.gz
[main] Real time: 9.389 sec; CPU: 63.959 sec
----------------REF GRAPH CONSTRUCTION--------------
java.lang.NullPointerException
        at HLASequence.<init>(HLASequence.java:17)
        at MergeMSFs.formDataBase(MergeMSFs.java:39)
        at HLA.loadGraphs(HLA.java:91)
        at HLA.<init>(HLA.java:62)
        at HLA.main(HLA.java:556)

```

**Comment by hsiaoyi0504** [comment]
I meet the same issue. Does anyone know how to solve this?

**Comment by lenapfitzer** [comment]
I have the same issue after updating the HLA reference from IMGT HLA alignments version 3.36.0 to 3.41.0. Any ideas?

**Comment by heewookl** [comment]
There will be an update released sometime next month to address this issue.
